### ISSUE TITLE
Is the preprocess alignment necessary?

### ISSUE THREAD

**Issue by luohao123** [keonlee9420/PortaSpeech#12]
for multispeaker dataset train tts, is this preprocess alignment necessary? This provided preprocess script support Chinese?

**Comment by keonlee9420** [comment]
Sorry for the late response. In theory, you can specify the speakers at inference time after training the speaker embedder. For more details, I'd like to recommend you refer to my other repos where the model handles multi-speaker datasets such as VCTK first. You may start from my [Tacotron2](https://github.com/keonlee9420/Comprehensive-Tacotron2), or [FastSpeech2](https://github.com/keonlee9420/Comprehensive-Transformer-TTS) related projects.

**Comment by keonlee9420** [comment]
Close due to inactivity.
