### ISSUE TITLE
Weird  sound from the beginning of the sentence "hello"

### ISSUE THREAD

**Issue by johnkuan506** [keonlee9420/PortaSpeech#14]
Hi, thanks for your contribution in TTS, and it's such a great work !!
It's seems perfect in most of the sentence while trying ```python3 synthesize.py --text "MY_SENTENCE" --restore_step 125000 --mode single --dataset LJSpeech```, but when I tried the sentence with "hello" in the front, the sound of "hello" became long and weird. Here is the mel-spetrogram of "Hello, glad to see you." 
![](https://i.imgur.com/bw9jr7l.png)
And you can observe a large area on the left is represent the word "hello" clearly.
I've tried to check your training data in preprocessed_data/LJSpeech/train.txt, and I couldn't find the word "hello" in that.

Is this problem caused by the quantity of the phoneme of the word merely or I just do something wrong or something else?
Anything would help, thank you.

**Comment by keonlee9420** [comment]
Hi @johnkuan506 , thanks for the report. You might be done correctly for the synthesis if the output speech contains all the words in the input text. I think this comes from both: that input was unseen during training and the issue mentioned [here](https://github.com/keonlee9420/PortaSpeech/issues/3#issuecomment-950599642). I'll put my effort soon, but of course, you can try first and PR for the community.

**Comment by keonlee9420** [comment]
@johnkuan506 , I just updated the repo with the fixation (there was a bug in code, see this [commit](https://github.com/keonlee9420/PortaSpeech/blob/c2d1131d7a1e539c062ac2d6fbe3aed143f038b5/model/linguistic_encoder.py#L193)). I also applied several techniques to improve the alignment (see the note section in README for the details). So please check out the new pre-trained model and demo!

Here is the output mel of "Hello, glad to see you." using the update:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/34522972/153815906-a4792ace-37d2-403d-8b5b-1498b7e2e8af.png">

**Comment by johnkuan506** [comment]
Hi @keonlee9420, thank for your work. I've tried some sentences, and these changes do improve PortaSpeech's generalization ability on untrained data. I'll let you know if I find any problems.

**Comment by keonlee9420** [comment]
> Hi @keonlee9420, thank for your work. I've tried some sentences, and these changes do improve PortaSpeech's generalization ability on untrained data. I'll let you know if I find any problems.

thanks for your effort!

**Comment by keonlee9420** [comment]
Close due to inactivity
