### ISSUE TITLE
A run Problem(LJSpeech)

### ISSUE THREAD

**Issue by yanzhuangzhuang-beep** [keonlee9420/PortaSpeech#16]
File "preprocess.py", line 20, in <module>
    preprocessor.build_from_path()
  File "D:\UW-Detection\PortaSpeech\preprocessor\preprocessor.py", line 129, in build_from_path
    n_frames += n
UnboundLocalError: local variable 'n' referenced before assignment
 when I use NATSpeech show this problem (BiaoBei dataset)
when I use LJSpeech dataset and this code show this problem
I use global but cannot ......

**Comment by keonlee9420** [comment]
Hi @yanzhuangzhuang-beep , this seems to happen when you don't have TextGrid with the current filename in the expected directory. Could you please make sure that you have that in the correct location?

**Comment by yanzhuangzhuang-beep** [comment]
thanks
